name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: lint
      run: make lint
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: make test