name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: latest
        args: --exclude-use-default=false --disable-all --enable=golint
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: test
      run: make test